### ISSUE TITLE
Empty msgid with msgctxt throws error

### ISSUE THREAD

**Issue by AHagemannCK** [adams85/po#14] opened 2021-09-20 15:14 UTC
Hi there,

Parser is not working as it should according to POedit (https://github.com/vslavik/poedit/issues/97).
This po file **should be valid** (can be opened and edit in POedit):
msgid ""
msgstr ""
"Content-Transfer-Encoding: 8bit\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Language: en_US\n"
"Project-Id-Version: \n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"X-Generator: Poedit 3.0\n"

msgctxt "EmailTemplateLanguage_SurveyURL_1"
msgid ""
msgstr "SurveyUrl Update Test"

msgctxt "EmailTemplateLanguage_Subject_1"
msgid "TEST"
msgstr "Subject Update Test"

msgctxt "EmailTemplateLanguage_Content_1"
msgid "TEST"
msgstr "Content Update Test"

**Still parser throws:**
Entry beginning at {0} must not have an empty id.

Can you help me with this?

Thank you very much!

**Comment by AHagemannCK** [comment] 2021-09-20 16:12
https://github.com/adams85/po/pull/15

Fixed with PR 15

**Comment by adams85** [comment] 2021-09-21 15:14
Hi!

First of all, thank you for pointing this edge case out. POEdit accepts this input indeed, however, I noticed some weird behavior: if you treat this as a PO template and create a new translation file from it (_File_ / _New from POT/PO file..._), you get this result:

![image](https://user-images.githubusercontent.com/31276480/134187594-64255cef-67d0-42a7-a530-5da22b176932.png)

As you can see, the entry with the empty id and non-empty context is there but somehow it gets mixed up with the header entry, whose contents are displayed in the _Translation_ column. It seems that POEdit itself has some issues getting this edge case right, thus, I don't think it's a good idea to pursue this unusual use case...

Apart from this, of course, we can (and probably should fix) this in the lib but I'm afraid it's not that simple as your PR suggests it.

**Comment by adams85** [comment] 2021-09-22 21:54
The issue is fixed by commit https://github.com/adams85/po/commit/bc33caef8c37e204dfdb98f9c6fb8de19b52281e and the fix will be released soon in v1.8.0.

From now on only the `msgid ""`, missing `msgid_plural` and missing `msgctxt` combination (which corresponds to `new POKey(string.Empty, null, null)`) is treated as a special key (reserved for header entry), every other combination with an empty id is accepted after the header entry.

**Comment by adams85** [comment] 2021-09-25 19:05
FYI, v1.8.0 has been released.

**Closed by adams85** 2021-09-25 19:05 UTC
